---
- name: Install RANS packages
  hosts: localhost
  become: true
  tasks:
    - name: Install Nginx
      dnf:
        name: nginx
        state: present
      tags:
        - nginx

    - name: Add ArangoDB repository
      command: curl -OL https://download.arangodb.com/arangodb310/RPM/arangodb310.repo
      args:
        chdir: /etc/yum.repos.d/
      tags:
        - arangodb

    - name: Install ArangoDB Server
      dnf:
        name: arangodb3-3.10.5-1.0
        state: present
      tags:
        - arangodb

    - name: Secure installation
      command: ARANGODB_DEFAULT_ROOT_PASSWORD=root arango-secure-installation
      tags:
        - arangodb

    - name: Install Rust
      command: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      args:
        creates: /home/{{ ansible_user }}/.cargo/bin
      tags:
        - rust

    - name: Enable and start Nginx service
      systemd:
        name: nginx
        enabled: yes
        state: started
      tags:
        - nginx

    - name: Enable and start ArangoDB service
      systemd:
        name: arangodb3
        enabled: yes
        state: started
      tags:
        - arangodb

    - name: Configure HTTP Firewall
      become: true
      firewalld:
        port: 80/tcp
        permanent: yes
        state: enabled
        immediate: yes
      tags:
        - arangodb

    - name: Configure ArangoDB Firewall
      become: true
      firewalld:
        port: 8529/tcp
        permanent: yes
        state: enabled
        immediate: yes
      tags:
        - arangodb
